spring:
  profiles:
    active: dev
logging:
  level:
    root: INFO
    '[com.automation]': TRACE
    file: DEBUG
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n'

